{"name": "test_add_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 9\n +  where 10 = add(3, 7)", "trace": "def test_add_02():\n>       assert add(3, 7) == 9\nE       assert 10 == 9\nE        +  where 10 = add(3, 7)\n\ntest_pytest_01.py:20: AssertionError"}, "start": 1607615402752, "stop": 1607615402752, "uuid": "6745ba33-0552-43f7-bb12-49150ab1c2ee", "historyId": "76dec9353c06cd1f119643a3957d3851", "testCaseId": "03d48502097bb1eaa0178ef93ae723b8", "fullName": "test_pytest_01#test_add_02", "labels": [{"name": "suite", "value": "test_pytest_01"}, {"name": "host", "value": "luonan0706"}, {"name": "thread", "value": "18068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest_01"}]}